### PR TITLE
Fixed post-build event failing

### PR DESCRIPTION
**Pull request by alimbada**
Post build file copies were causing build failures. Using $(SolutionDir) macro instead of relative paths instead now.

### CODE REVIEW

**Comment by devstator82** [comment]
Have you tried selecting the x86 target in the configuration manager dropdown? That should have allowed you to build correctly. Let me know if it doesn't

**Comment by alimbada** [comment]
Yeah, went back to your commit, switched to x86 and I'm getting a bunch of bogus build errors now saying it can't find a load of types. What's weird is going back to AnyCPU doesn't give me the original errors that caused me to submit this fix.

I'm in the "Inbox2 Client Only.sln" on a 64-bit machine, by the way. I'm not sure which solution I'm supposed to be using.

**Comment by ghost** [comment]
I'm in the same situation as you are alimbada, also using the "Inbox2 Client Only.sln". The following might help you get started.

Firstly, the post build events for the "Inbox2.Plugins.*" Projects and the "Inbox2.Core.LauncherCommands" Project had a relative destination path which was missing a directory. Try replacing the current post-build event with the following in all the aforementioned projects:

copy "$(TargetDir)_._" "..............\Code\Client\Inbox2\$(OutDir)"

This should help you get rid of ".... exited with code 1 something" errors when building.

After that you'll get a BadImageException of SQLLite when you start debugging. That error in turn can be fixed by manually copying the file:

ThirdParty\Sqlite\x64\System.Data.SQLite.DLL

To the directory:

Code\Client\Inbox2\bin\Debug\

Replacing the existing one. There's probably an easier way, but at least you'll be able to start it for now. Good luck :)

**Comment by alimbada** [comment]
raytheon, that's all well and good, but I'm curious to know why I need to jump through these hoops to get the solution building and running. What's wrong with using $(SolutionDir) instead of a relative path?

At the very least there should be some build instructions in the readme to get people started.

I had the BadImageFormatException too, but I think it went away after I did a clean and rebuild. I thought it was just something weird on my machine so I didn't bother reporting it.

**Pull request closed without merging**
